# Version information.
settings_version:   0.1.0
# Info.
program_name:       "Hidey-Ho"
program_ver:        0.0.1
program_devs:       ["Michael Cvitanovich"]
program_web:        "galacticwingcommander"    
# Code embedding settings.
max_embed_ratio:    0.5
min_capacity:       1000
prog_code:          "PICCODER"
byte_chunk:         50000
secret_folder:      "./secret"
thumb_folder:       "./images"
# UI settings.
window_width:       1000
window_height:      700
