# Version information.
settings_version:   0.1.0
# Code embedding settings.
max_embed_ratio:    0.5
min_capacity:       1000
prog_code:          "PICCODER"
pw_hash_len:        32
byte_chunk:         50000
